### ISSUE TITLE
Commits are too noisy.

### ISSUE THREAD

**Issue by falfaddaghi** [AyhamRatrout/Stack#1]
you needed to push a lot more files than just the ones you wrote. 
do you know why this is the case?

**Comment by AyhamRatrout** [comment]
For the commits are too noisy bit, I'm assuming this is because I wrote the whole project, tested it, then just pushed it all in one commit?

For the a lot more files part, is it because I needed to add .gitignore file? And what other files should I have pushed?

**Comment by falfaddaghi** [comment]
correct on both.
you need to add an ignore file.
you can find them here https://github.com/github/gitignore
